### PR TITLE
[#420] Add support for clojure.core/find-var

### PR DESCRIPTION
**Pull request by RickMoynihan**

### CODE REVIEW

**Comment by borkdude** [comment]
@RickMoynihan Nice try :) But this won't work. Sci has its own implementation of vars and there is no one global runtime like in Clojure. See implementations of other namespace related stuff: https://github.com/borkdude/sci/blob/2f3760eb7c3f129adf044dadbe75ebed5f27921f/src/sci/impl/namespaces.cljc#L487-L516.
I think instead of resolving anything, this is just a matter of looking up an entry in a map.

Sci has one `ctx` map which contains an `:env` atom which contains all the `:namespaces` (e.g. `foo.bar`) which in turn contains a map of symbols to vars (or just plain values).

**Comment by borkdude** [comment]
@RickMoynihan 

I think these come relatively close:

https://github.com/borkdude/sci/blob/master/src/sci/impl/namespaces.cljc#L363-L378

For testing, it might be better to just return a boolean and do the comparison within the program itself, since sci is also tested as a binary of which output is serialized via EDN.

**Comment by RickMoynihan** [comment]
Ah thanks, I'd meant to open the PR as a draft to access your CI.

I'd seen those for `resolve` etc and had wondered about them.  I didn't think it would be quite this easy :-)  I'll take a look at them and see if I can work out what's going on.

**Comment by borkdude** [comment]
Looks good. Could add some error handling. Compare to Clojure:

``` 
user=> (find-var '+)
Execution error (IllegalArgumentException) at user/eval1 (REPL:1).
Symbol must be namespace-qualified
 
user=> (find-var 'foo/bar)
Execution error (IllegalArgumentException) at user/eval143 (REPL:1).
No such namespace: foo
```

**Comment by RickMoynihan** [comment]
👍 that would definitely be a good idea I'll try to take a look at that later.

**Pull request merged**
