### PR TITLE
interpret: use inner functions for each case

### PR DESCRIPTION
**Pull request by viebel**
I like to introduce inner functions to make the code more easy to read.
It allows the reader to be uncurious in the sense that she can read the code of a function without being required to drill down into all the details.

I learned about this approach from Chapter 3 (about functions) in [Clean Code: A Handbook of Agile Software Craftsmanship](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)

Let me know if it makes sense to you @borkdude .

### CODE REVIEW

**Comment by borkdude** [comment]
@viebel Fine by me if you can bring this PR up to date.

**Comment by viebel** [comment]
PR updated. Feel free to merge one CircleCI reports a OK status @borkdude

**Comment by borkdude** [comment]
Maybe you can try to force push something one more time, I think a default setting of CircleCI didn't build PRs, I turned that off now.

**Comment by viebel** [comment]
@borkdude CircleCI is green!

**Pull request merged**
