### PR TITLE
Add clojure.walk/macroexpand-all

### PR DESCRIPTION
**Pull request by kwrooijen**
fixes https://github.com/borkdude/sci/issues/389

### CODE REVIEW

**Comment by kwrooijen** [comment]
@borkdude Should this be wrapped in `#?(:clj ,,,)` ?

**Comment by borkdude** [comment]
@kwrooijen Like I said yesterday on slack: don't use Clojure's macroexpand-all, because that is going to run Clojure's macroexpand. Sci has its own macroexpand, so you'll need to re-implement macroexpand-all calling that one.

**Comment by kwrooijen** [comment]
All right, will get back to this

**Comment by kwrooijen** [comment]
A problem I'm seeing is that I can't require `sci.impl.interpreter` in `sci.impl.namespaces` because of cyclic dependencies. We'd have to move some code around if we want to implement it ourselves I think?

**Comment by borkdude** [comment]
@kwrooijen I solved the exact same problem for `require`, so you can take that as an example.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/sci/commit/8a57faafa9f69e62c3f8335677d56820c58717a9

**Pull request closed without merging**
